source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
target 'NewAfar' do

pod 'AFNetworking', '~> 4.0.1'
pod 'Toast', '~> 3.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SDCycleScrollView', '~> 1.65'
pod 'KissXML', '~> 5.1.2'
pod 'DXPopover', '~> 0.1.1'
pod 'pop', '~> 1.0.9'
pod 'Masonry', '~> 1.0.1'
pod 'MJRefresh', '~> 3.1.12'
pod 'SDAutoLayout', '~> 2.1.7'
pod 'IQKeyboardManager', '~> 6.5.6'
pod 'FDFullscreenPopGesture', '~> 1.1'

end
